apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3-liq-laf-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v3-liq-laf-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: v3-liq-laf-1
    spec:
      containers:
        - name: v3-liq
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: NODE_OPTIONS
              value: --max_old_space_size=4096
            - name: CLUSTER
              value: mainnet
            - name: GROUP
              value: mainnet.1
            - name: INTERVAL
              value: "2500"
            - name: LIAB_LIMIT
              value: "0.7"
            - name: MIN_EQUITY
              value: "0.2"
            - name: LIQUIDATABLE_FEED_WEBSOCKET_ADDRESS
              value: ws://10.121.128.69:9123
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: v3-liq-laf
                  key: private-key
            - name: ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: v3-liq-laf
                  key: endpoint-url
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: v3-liq-laf
                  key: webhook-url